### ISSUE TITLE
NSGA3 elitism - initial sampling does not survive.

### ISSUE THREAD

**Issue by AbtinShH** [anyoptimization/pymoo#180]
I am coupling the pymoo NSGA3 with pyswmm to optimize 5 objectives. I have input two extreme populations as initial set of solutions for sampling in the algorithm and I want them to survive and be in the last set of optimized solutions.
However, they survive only for small number of generations (5) but not for greater number of generations (>10). How can I enforce elitism to ensure that these two initial populations will survive through the last generation?
I appreciate your help with this.

**Comment by julesy89** [comment]
I have seen you have also sent me an E-Mail. Let us continue the discussion here.

What is the reason why they shall survive? They are eliminated because solutions either dominate them (most likely if early during the convergence phase) or later to improve the diversity. 

NSGA3 is an elitist algorithm, and of course, elitism is enforced in each generation. 

However, if you want these solutions to participate in mating, you can use the object-oriented interface (https://pymoo.org/getting_started.html#Object-Oriented-Interface ) or the Callback (https://pymoo.org/interface/callback.html ) and add them in each iteration again.

**Comment by andresliszt** [comment]
If you use NSGA3 in ``pymoo``, the selection is default in ``TournamentSelection(func_comp=comp_by_cv_then_random)``, so
if you have a good solution for one of the objectives, it is no guarantee that it will survive to the last generation, because the tournament is random, and dosent matter the fitness values. Maybe you can use ``TournamentSelection(func_comp=binary_tournament)``  which is the default selection in the NSGA2 algorithm

**Comment by julesy89** [comment]
That is not correct. You are right that NSGA3 uses the `TournamentSelection,` but this is the **MATING** selection and not the **ENVIRONMENTAL** selection/survival. The `ReferenceDirectionSelection` chooses first non-dominated individuals and then the closest one to each reference line. If then a second solution is selected for a line, then randomly, a solution assigned to this line is taken. Please see the paper for more details.

**Comment by andresliszt** [comment]
You're right, I deleted my comment because as soon as I wrote it I realized it was wrong
