### ISSUE TITLE
ASF and AASF calculation

### ISSUE THREAD

**Issue by nbena** [anyoptimization/pymoo#190]
Hello
First of all thanks for the great library. I have a question regarding how ASF and AASF are computed. By searching the literature I noticed that there are several versions of such functions, especially for AASF (despite being quite similar after all). My question is about weights, why are they used as the denominator? The few times I have seen those formula with a denominator, it was for reference vectors not weights. Furthermore, other works stress the fact that typically weights are not used (but eventually *normalization factors*). Can you help me in understanding which formula are you using? I read the reference mentioned on the website, but it contains a bit too math for me :)
Thanks

**Comment by julesy89** [comment]
Both are valid definitions for ASF and AASF. I asked myself the same question when implementing it. NSGA3 uses for the normalization of the one where the values are divided by the weights. 

It is not that easy to explain in a comment here, but I will try by giving you two examples. Let us consider one weight vector each and what point they are trying to find in a three-dimensional objective space. 

- For instance, when multiplying with `w=(1,0,0)`we will get the minimum of the first objective because the zeros will cancel out the second and the third. This definition is quite intuitive.
- When dividing, it is first of all worth noting that we can not divide by zero. Let us consider `w=(0.998, 0.001, 0.001)` for instance. Now, something interesting, in fact, happens. The second and third objectives are highly punished by dividing by a rather small value (in practice, even much smaller). This results in a value where the second and third objective is minimal and the corresponding value of the first objective. This will be a Pareto-optimal (extreme) point and can be used to estimate the bounds of the Pareto-front (exactly that is how it is used in NSGA3), for instance.

I hope this was helpful.

**Comment by nbena** [comment]
I got the point!
Thanks
