### ISSUE TITLE
Crossover for Assignments

### ISSUE THREAD

**Issue by athenawisdoms** [anyoptimization/pymoo#267]
Hi, I'm new here and hope to get some help applying GA to an assignment problem, specifically with the crossover operator that does not violate the constraints that each agent should not be assigned to more than 1 task, or each task should not be assigned to more than 1 agent.

Is there such a crossover operator available? I looked at the Subset Selection Problem example but I cant figure out the custom crossover operator that we need here...

Any help will be immensely helpful! Thanks!

**Comment by julesy89** [comment]
Thanks for considering using pymoo! You will have to implement the crossover by yourself.
The subset selection tutorial (as you have already mentioned) shall help you to do so. 

In your case, the row and column sum should be equal to one, which can be achieved by keeping track of all available assignment options during the crossover and eliminating the ones after the assignment. It might be easier to use an integer representation instead of 0's and 1's.
