### ISSUE TITLE
Elementwise, parallelizable mutation?

### ISSUE THREAD

**Issue by chajath** [anyoptimization/pymoo#340]
I happen to be working on a GA problem with a rather costly mutation. Unlike the problem definition, I don't see any parallelizable mutation implementation. Is there any plan or interest in making mutation element-wise and parallelizing? I'll be happy to contribute. Since I get the reference to `problem` in the mutation, I guess I can use the `elementwise_runner` of the problem instance.

**Comment by blankjul** [comment]
Just curious, what is the mutation you have implemented? 

Most mutations I have implemented are written already vectorized (because the input is always the whole population).
If that is not possible, then using threads is a good option! You might also want to check out `joblib` which has a nice API for parallelization as well.
