### ISSUE TITLE
Multiobjective differential evolution

### ISSUE THREAD

**Issue by altaris** [anyoptimization/pymoo#367]
Hello,

[pymoo's differential evolution](https://pymoo.org/algorithms/soo/de.html#nb-de) algorithm is single objective. Is there a way to use it for multi-objective problems? Something in the vein of DEMO [^demo]?

[^demo]: Robič, T., Filipič, B. (2005). DEMO: Differential Evolution for Multiobjective Optimization. In: Coello Coello, C.A., Hernández Aguirre, A., Zitzler, E. (eds) Evolutionary Multi-Criterion Optimization. EMO 2005. Lecture Notes in Computer Science, vol 3410. Springer, Berlin, Heidelberg. https://doi.org/10.1007/978-3-540-31880-4_36

**Comment by bruscalia** [comment]
Hi, @altaris! If I might anticipate some response, I'm planning to include a few multi-objective differential evolution algorithms in the next releases of pymoo, but not DEMO itself (for now). DEMO is incompatible with the "ask and tell" interface because it updates the population immediately after each new individual is produced so that it can take part in the mating of new individuals (not once for the entire population at each generation). However, next releases are likely to have GDE3, NSDE, and NSDE-R. 

You can find these algorithms already implemented here: https://github.com/mooscaliaproject/pymoode

**Comment by altaris** [comment]
Hello @bruscalia 👋 

> because it updates the population immediately after each new individual is produced

Maybe it doesn't have to. I tried implementing this, and my idea was to 
1. in `Algorithm._infill` create a new individual by mating&crossover, and keep the index of the parent in the `Individual.data` dict;
2. in `Algorithm._advance` (so once the new individual has been evaluated), retrieve the parent, see if the offspring dominates the parent, and replace as required.
Now, I'm not very familiar with pymoo's internals, so my implementation does not work for some reason. I think it has to do with feasibility and probably the fact that I don't use all of pymoo's facilities e.g. crossover and mating classes. But anyway, what do you think of this approach?

Cheers,

**Comment by bruscalia** [comment]
Hi @altaris!

It would be very nice if your implementation works! The main challenge I had so far was that it is likely that we would not be able to re-use all other reproduction operators of DE because of adding individuals "step-by-step" (not only a child might immediately replace the corresponding parent, but the population size might be temporarily increased). Probably, reproduction in a DEMO implementation would occur in the _next method (as in g3pcx) which inherits from LoopwiseAlgorithm.

Let me know if you have some advance!
