### ISSUE TITLE
U-NSGA-III Verbose=True error

### ISSUE THREAD

**Issue by corsair20141** [anyoptimization/pymoo#432]
When argument `Verbose=True` is applied to the `minimize()` method using UNSGA3 algorithm, the following error is encountered after the first iteration (generation):

```ValueError: zero-size array to reduction operation minimum which has no identity```

**Comment by corsair20141** [comment]
Additionally: It is not just related to `Verbose=True`, there is a deeper problem. With `Verbose=False` the minimization routine runs, but it appears only the initial population is kept so very few non-dominated solutions occur.

Is this a bug or is it improper use on my end?

n_obj = 2
n_ineq = 1
n_var = 4

**Comment by blankjul** [comment]
Can you please provide an example for us to reproduce the error? It is hard to guess what can cause the error above without any indication.

```
import numpy as np

from pymoo.algorithms.moo.unsga3 import UNSGA3
from pymoo.optimize import minimize
from pymoo.problems import get_problem

problem = get_problem("ackley", n_var=30)

ref_dirs = np.array([[1.0]])

algorithm = UNSGA3(ref_dirs, pop_size=100)

res = minimize(problem,
               algorithm,
               termination=('n_gen', 150),
               verbose=True,
               seed=1)

print("UNSGA3: Best solution found: \nX = %s\nF = %s" % (res.X, res.F))
```

This is an example from the documentation that works. I have a feeling the error could be related to the constraint. Could other algorithms solve your problem? (just to be sure the problem is defined the right way).

**Comment by corsair20141** [comment]
Thank you for your response. Yes, that example code runs fine for me as
well. However, with my specific problem the UNSGA3 algorithm has issues.
The NSGA2 algorithm worked fine for my constrained optimization problem, as
did CTAEA. Could it be because I have the problem defined as an
'element-wise problem'?

**Comment by blankjul** [comment]
Thanks for the clarification. It seems to be a U-NSGA3-specific problem then. Can you provide some simple code to reproduce the problem? The information above will not be enough for me to analyze when what goes wrong.

**Comment by blankjul** [comment]
wow. that is a really interesting problem. It actually is because of `NSGA3`. 

So in `NSGA3` the optimum is based on a solution being
- non-dominated
- the closest to a reference direction

Now, what happens is that no solution that is non-dominated is closest to a reference direction. Thus, there is no true optimum which brings some trouble later. Can you check if it woks with the commit above?

Technically, this can still make throw an exception if this happens in the very first interaction I think.
