### ISSUE TITLE
Making Mixed Variables Faster/Use Numpy More Efficiently

### ISSUE THREAD

**Issue by CompRhys** [anyoptimization/pymoo#445]
> Originally, I was not planning to add mixed variables because it breaks whenever a numpy array is expected.

Our needs have evolved to need to tackle a mixed variable problem, this appears to necessitate passing each argument as a var which will seemingly prevent vectorization. An initial idea would be to reorder the operations such that the top level of the vars dict becomes keys indicative of type e.g. `real` and then these could store arrays that would be processed as arrays. For high dimensional problems like ours (~100d) this would cut the python loop from ~n_types*100 to n*types allowing much better use of numpy. I wondered what considerations were taken into account in arriving at the current solution and whether there scope to improve the framework that exists. For our problem it does seem feasible to hack around and use a repair operation to quantize a subset of the continuous parameters to represent our discrete and categorical parameters but this seems like a non-ideal solution.

**Comment by blankjul** [comment]
For mixed variables, the following solution exists:
https://pymoo.org/customization/mixed.html

However, the code is a more or less "hacky" solution because originally pymoo was not designed for mixed-variable problems. The mating will group variables of the same type e.g. all floats or integers and so on, together and then perform the evolutionary operators group-wise. For performance, a repair operator is probably the better choice.
