### ISSUE TITLE
gradient.deactivate() setting wrong name?

### ISSUE THREAD

**Issue by corecode** [anyoptimization/pymoo#463]
I think the string should read `"autograd.numpy"`.

https://github.com/anyoptimization/pymoo/blame/6fac683d5b9cc8f5c4088e8ad62d01da1cd0a696/pymoo/gradient/__init__.py#L19

**Comment by blankjul** [comment]
No this is in fact correct. If automatic differentiation should be disabled then we directly use numpy. Otherwise, we need to use the implementation that should be used (e.g. autograd or Jax). 

This probably can even be removed because we added this to test Jax, but it ended up being a lot slower in our tests.

**Comment by blankjul** [comment]
Has changing this line fixed an issues you are facing?

**Comment by corecode** [comment]
No, I just came across it while trying to figure out autograd.
