### ISSUE TITLE
error in brkga pymoo implementation

### ISSUE THREAD

**Issue by avelin0** [anyoptimization/pymoo#499]
Hello, it appear this error when trying to run brkga pymoo code https://pymoo.org/algorithms/soo/brkga.html 

--------------------------------------------------------------------------------
runcell(0, 'C:/Users/avelino/OneDrive/FINAL/untitled0.py')
Sorted by [ 1 19 12 14  6  9  8  5  4  3  0 17 13 11  2  7 10 15 18 16]
Traceback (most recent call last):

  File ~\anaconda3\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File c:\users\avelino\onedrive\final\untitled0.py:48
    res = minimize(problem,

  File ~\anaconda3\lib\site-packages\pymoo\optimize.py:67 in minimize
    res = algorithm.run()

  File ~\anaconda3\lib\site-packages\pymoo\core\algorithm.py:141 in run
    self.next()

  File ~\anaconda3\lib\site-packages\pymoo\core\algorithm.py:157 in next
    infills = self.infill()

  File ~\anaconda3\lib\site-packages\pymoo\core\algorithm.py:193 in infill
    infills = self._infill()

  File ~\anaconda3\lib\site-packages\pymoo\algorithms\soo\nonconvex\brkga.py:141 in _infill
    off = self.mating.do(self.problem, pop, n_offsprings=self.n_offsprings, algorithm=self)

  File ~\anaconda3\lib\site-packages\pymoo\core\infill.py:38 in do
    _off = self._do(problem, pop, n_remaining, **kwargs)

  File ~\anaconda3\lib\site-packages\pymoo\core\mating.py:31 in _do
    off = self.crossover(problem, parents, **kwargs)

  File ~\anaconda3\lib\site-packages\pymoo\core\operator.py:27 in __call__
    out = self.do(problem, elem, *args, **kwargs)

  File ~\anaconda3\lib\site-packages\pymoo\core\crossover.py:31 in do
    X = np.swapaxes(np.array([[parent.get("X") for parent in mating] for mating in pop]), 0, 1)

  File ~\anaconda3\lib\site-packages\pymoo\core\crossover.py:31 in <listcomp>
    X = np.swapaxes(np.array([[parent.get("X") for parent in mating] for mating in pop]), 0, 1)

  File ~\anaconda3\lib\site-packages\pymoo\core\crossover.py:31 in <listcomp>
    X = np.swapaxes(np.array([[parent.get("X") for parent in mating] for mating in pop]), 0, 1)

AttributeError: 'numpy.int64' object has no attribute 'get'

**Comment by Omastto1** [comment]
Hello, i have encountered this error just now as well.
I have been able to pinpoint the cause of this.
in `pymoo.core.selection.Selection.do` method there is this code on line 52
```
if to_pop and isinstance(ret, np.ndarray) and ret.dtype == int:
   ret = pop[ret]
```
which check whether `ret.dtype` is int.
However, the output of `elitebiasedselection`, which BRKGA uses, is `np.ndarray` with `dtype=np.int64` and as result, the condition on line 52 above is evaluated to False.
Here, `pop` is list of `pymoo.core.individual.Individual` objects, and `rect` is list of indices.
What happens is that, since the condition is evaluated to False, the `ret` variable remains list of indices instead of list of individuals.
Later on in the `pymoo.core.crossover.Crossover.do` method, there is this code on line 31
`X = np.swapaxes(np.array([[parent.get("X") for parent in mating] for mating in pop]), 0, 1)`
which expects each `pop` array element to be instance of a class that contains `X` variable, but in this case the `pop` is still an array containing indices (integers) and the line raises the error you provided.

Going back to `elitebiasedselection` 
I pinpointed the issue to this module `pymoo.algorithms.soo.nonconvex.brkga.elitebiasedselection._do`
```
def _do(self, problem, pop, n_select, n_parents, **kwargs):
        _type = pop.get("type")
        elites = np.where(_type == "elite")[0]
        non_elites = np.where(_type == "non_elite")[0]
```
Here, the `np.where(_type == "...")[0]` calls create `np.int64` `np,ndarray`'s
So the solution seems to be either
a) cast `elites` and `non_elites` to `int`,  with `np.ndarray.astype(int)`, or  
b) change the condition in the top of this comment to `ret.dtype in [int, np.int64] ` or similar

**Comment by blankjul** [comment]
Can you check if the last commit resolved the issue?

**Comment by avelin0** [comment]
I will do It tomorrow, thank you in advance.

**Comment by blankjul** [comment]
Did this resolve the issue?

**Comment by avelin0** [comment]
yes, both alternatives resolve the issue

Em qua., 22 de nov. de 2023 às 02:07, Julian Blank ***@***.***>
escreveu:
