### ISSUE TITLE
Pareto front

### ISSUE THREAD

**Issue by faranak1991** [anyoptimization/pymoo#546]
Hello,

my problem has 5 objective functions, and upon running the provided script, my expectation is to generate a set of Pareto front solutions. Is this understanding accurate? Additionally, what factors influence the number of Pareto front solutions? I see that it is contingent upon the population size, with the number of Pareto front solutions being equivalent to the population size. For example by choosing 10 pop size, shows up the 10 Best solutions.!!

class MyCallback(Callback):
    def __init__(self) -> None:
        super().__init__()
        self.data["best"] = []

    def notify(self, algorithm):
        self.data["best"].append(algorithm.pop.get("F").min())
        
res = minimize(problem,
               algorithm,
               termination=termination,  # Pass termination here
               callback=MyCallback(),
               seed=1,
               output=MyOutput(),
               save_history=True,
               verbose=True)  

print("Best Solution (X):", res.X)
print("Best Objective (F):", res.F)

**Comment by blankjul** [comment]
Please open a discussion instead of an issue next time. This seems to be a question about how evolutionary algorithms actually work, rather than an issue with pymoo.

For most algorithms the population size will be the upper bound of number of (optimal) solutions that will be returned. However, an algrithm can also define an external archive and store solutions there as well (this is what you might want to implement in a `Callback`).

It sounds like that you want more solutions. For a problem with 5 objectives, you can define for instance 1000 reference directions and instantiate NSGA-III with them (with a population size of at least 1000). Then the upper limit of non-dominated solutions returned as optimal will be 1000 (note that this may be also different from algorithm to algorithm).
