### ISSUE TITLE
Parallelization improvement

### ISSUE THREAD

**Issue by fremk** [anyoptimization/pymoo#598]
Hello, I am currently working on a problem with 27 variables and 17 inequality constraints. I am experimenting with large population sizes (~10k individuals) and trying to solve it using MixedVariableGA genetic algorithm. 
I have my evaluation function (objective function) parallelized via GPU, (the objective function is linked to the output of a neural network) therefore I batch the full population and send it altogether through the GPU resulting in ~10 seconds of inference time for the evaluation of the full population. 
Surprisingly the minimization process still takes so much time (3 minutes per generation), and if my guess is correct it is due to the time it takes to generate the new generation based on the old one (since we have a big population size) via mating, mutation, crossover etc... 
So my question is, is there any way to speedup the 'creation' of the next generation of individuals? 

Thank you for your time,
Karim

**Comment by blankjul** [comment]
The creation for MixedVariables is more expensive because different matings (one for each variable type) have to be combined. 
The combined mating is implemented here: https://github.com/anyoptimization/pymoo/blob/main/pymoo/core/mixed.py

Have you ever profiled your code and see what function has the biggest bottleneck? 
It might be SBX and you can try to swap it out with a faster crossover if desired.

Otherwise, you can always implement your custom mating as well and optimize it for speed (just inherit from `MixedVariableMating`)

**Comment by fremk** [comment]
Thank you for your prompt reply!
I managed to reformulate the problem in such a way that it can be solved using GA with integer variables only, instead of MixedVariableGA and that lead to a significant increase in speed (~22 seconds per generation instead of ~3 minutes). Leaving around ~8 seconds for population creation and ~14 seconds for setting up NN input and NN inference.
Seems like it was indeed the MixedVariableGA mating.
Here's the algorithm with the current parameters that I am using. 
```
algorithm = GA(pop_size=population_size,
            sampling=IntegerRandomSampling(),
            crossover=SBX(prob=1.0, eta=3.0, vtype=float, repair=RoundingRepair()),
            mutation=PM(prob=1.0, eta=3.0, vtype=float, repair=RoundingRepair()),
            eliminate_duplicates=True,
            )
```
Can you recommend any changes that can speed up the creation of the generation even more? Like which crossover is faster than SBX? Or even other algorithms that might be faster than GA (?) 
I'm quite new to this domain so I appreciate all the help I can get :smile:

**Comment by blankjul** [comment]
If your problem is linear then you can use much more efficient solvers instead (instead of black-box optimization algorithms).  In pymoo `GA` is probably the best choice for this. However, there are for sure other frameworks more specialized on optimizing discrete problems (my research focus was mostly continous optimization).
