### ISSUE TITLE
install instructions

### ISSUE THREAD

**Issue by gnzsnz** [anyoptimization/pymoo#609]
I'm having problems with the install instructions for linux

```bash
$ docker run -it --rm python:3.12 bash
root@fab087e4e18b:/$ pip install pymoo "numpy<=1.26.4"
root@fab087e4e18b:/$ python -c "from pymoo.util.function_loader import is_compiled;print('Compiled Extensions: ', is_compiled())"
Compiled Extensions:  False
```

What works is to install cython

```bash
$ docker run -it --rm python:3.12 bash
root@cf04d691d8b3:/$ pip install pymoo "numpy<=1.26.4" cython # <- add cython
root@cf04d691d8b3:/$ python -c "from pymoo.util.function_loader import is_compiled;print('Compiled Extensions: ', is_compiled())"
Compiled Extensions:  True
```

**Comment by blankjul** [comment]
Thanks! I am pretty sure this is related to the `numpy` 2 release. I will have a look at this and see if I can make `pymoo` upwards compatible.

**Comment by blankjul** [comment]
I was not aware of the dependency before compilation. I think it should be this problem here:
https://stackoverflow.com/questions/54117786/add-numpy-get-include-argument-to-setuptools-without-preinstalled-numpy

Let me add a `pyproject.toml` file as well. We will see in the next release if it works.
